#lang s-exp "../grammar/v1.rkt"

(list)

(恣 p q (若 (且 (若 p q) p) q))
(恣 p q (若 (且 (若 p q) (非 q)) (非 p)))
(恣 p q r (若 (且 (若 p q) (若 q r)) (若 p r)))
(恣 p q (若 (且 (或 p q) (非 p)) q))
(恣 p q r s (若 (且 (若 p q) (且 (若 r s) (或 p r))) (或 q s)))
(恣 p q r s (若 (且 (若 p q) (若 r s) (或 (非 q) (非 s))) (或 (非 p) (非 r))))
(恣 p q r s (若 (且 (若 p q) (若 r s) (或 p (非 s))) (或 q (非 r))))
(恣 p q (若 (且 p q) p))
(恣 p q (若 p (若 q (或 p q))))
(恣 p q (若 p (或 p q)))
(恣 p q r (若 (且 (若 p q) (若 p r)) (若 p (且 q r))))
(恣 p q (若 (非 (且 p q)) (或 (非 p) (非 q))))
(恣 p q (若 (或 (非 p) (非 q)) (非 (且 p q))))
(恣 p q (若 (非 (或 p q)) (且 (非 p) (非 q))))
(恣 p q (若 (且 (非 p) (非 q)) (非 (或 p q))))
(恣 p q (若 (或 p q) (或 q p)))
(恣 p q (若 (或 q p) (或 p q)))
(恣 p q (若 (且 p q) (且 q p)))
(恣 p q (若 (且 q p) (且 p q)))
(恣 p q (若 (且 (等 p q) (若 q p)) (且 (若 q p) (若 p q))))
(恣 p q (若 (且 (若 q p) (若 p q)) (且 (若 p q) (若 q p))))
(恣 p q (若 (等 p q) (等 q p)))
(恣 p q (若 (等 q p) (等 p q)))
(恣 p q r (若 (或 p (或 q r)) (或 (或 p q) r)))
(恣 p q r (若 (或 (或 p q) r) (或 p (或 q r))))
(恣 p q r (若 (且 p (且 q r)) (且 (且 p q) r)))
(恣 p q r (若 (且 (且 p q) r) (且 p (且 q r))))
(恣 p q r (若 (且 p (或 q r)) (或 (且 p q) (且 p r))))
(恣 p q r (若 (或 (且 p q) (且 p r)) (且 p (或 q r))))
(恣 p q r (若 (或 p (且 q r)) (且 (或 p q) (或 p r))))
(恣 p q r (若 (且 (或 p q) (或 p r)) (或 p (且 q r))))
(恣 p (若 p (非 (非 p))))
(恣 p (若 (非 (非 p)) p))
(恣 p q (若 (若 p q) (若 (非 q) (非 p))))
(恣 p q (若 (若 (非 q) (非 p)) (若 p q)))
(恣 p q (若 (若 p q) (或 (非 p) q)))
(恣 p q (若 (或 (非 p) q) (若 p q)))
(恣 p q (若 (等 p q) (且 (若 p q) (若 q p))))
(恣 p q (若 (且 (若 p q) (若 q p)) (等 p q)))
(恣 p q (若 (等 p q) (或 (且 p q) (且 (非 p) (非 q)))))
(恣 p q (若 (或 (且 p q) (且 (非 p) (非 q))) (等 p q)))
(恣 p q (若 (等 p q) (且 (或 p (非 q)) (或 (非 p) q))))
(恣 p q (若 (且 (或 p (非 q)) (或 (非 p) q)) (等 p q)))
(恣 p q r (若 (若 (且 p q) r) (若 p (若 q r))))
(恣 p q r (若 (若 p (若 q r)) (若 (且 p q) r)))
(恣 p (若 p (或 p p)))
(恣 p (若 (或 p p) p))
(恣 p (若 p (且 p p)))
(恣 p (若 (且 p p) p))
(恣 p (或 p (非 p)))
(恣 p (非 (且 p (非 p))))
(恣 p q (若 (且 p (非 p)) q))
